"""
Output models — Layer 8 of the data processing pipeline.
Every LLM response is parsed into one of these Pydantic models.
"""
from __future__ import annotations

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ── Feature 1: Failure Report ─────────────────────────────────────────────────

class FailureFinding(BaseModel):
    step: str
    error_type: str
    occurrence_count: int
    root_cause: str                     # 1 sentence, factual, no invented numbers
    recommended_fix: str                # concrete action, not a process suggestion
    # Computed from Splunk data after LLM call — never generated by the LLM
    business_impact: str = ""


class FailureReport(BaseModel):
    program_id: str
    window_days: int
    total_executions: int
    success_rate_pct: float
    executive_summary: List[str]        # 3 bullets max
    critical_findings: List[FailureFinding]
    recurring_findings: List[FailureFinding]
    top_recommended_actions: List[str]  # max 5, ordered by priority
    # Computed from Splunk data after LLM call — never generated by the LLM
    estimated_hours_wasted: float = 0.0


# ── Feature 2: Risk Report ────────────────────────────────────────────────────

class StepRisk(BaseModel):
    step: str
    level: Literal["High", "Medium", "Low"]
    historical_failure_count: int = 0
    rationale: str = ""
    evidence: List[dict] = Field(default_factory=list)


class RiskReport(BaseModel):
    risk_level: Literal["High", "Medium", "Low"]
    most_likely_failure_step: str
    step_risks: List[StepRisk] = Field(default_factory=list)
    recommended_actions: List[str] = Field(default_factory=list)
    estimated_duration_min: Optional[int] = None
    narrative: str = ""
    reasoning: str = ""                 # concise causal rationale, not hidden chain-of-thought
    commit_sha: Optional[str] = None
    modules_at_risk: List[str] = Field(default_factory=list)


# ── Feature 3: Comparison Report ─────────────────────────────────────────────

class ExecutionSnapshot(BaseModel):
    id: str
    status: str
    pipeline: str
    duration_min: float
    failed_step: str
    error_type: str
    error_summary: str


class ComparisonReport(BaseModel):
    execution_a: ExecutionSnapshot
    execution_b: ExecutionSnapshot
    regression_introduced: bool
    likely_cause: str
    changed_files_relevant: List[str] = Field(default_factory=list)
    duration_delta_explanation: str
    recommended_action: str
    confidence: Literal["High", "Medium", "Low"]


# ── Feature 4: Correlation Report ────────────────────────────────────────────

class CorrelationHit(BaseModel):
    file_path: str
    line_no: Optional[int] = None
    code_snippet: Optional[str] = None
    relevance_explanation: str


class CorrelationReport(BaseModel):
    execution_id: str
    failed_step: str
    error_type: str
    error_summary: str
    source_files: List[CorrelationHit] = Field(default_factory=list)
    root_cause: str
    fix: str
    confidence: Literal["High", "Medium", "Low"]


# ── Feature 5a: Scan Report ───────────────────────────────────────────────────

class ScanFinding(BaseModel):
    severity: Literal["P1", "P2", "P3"]
    file: str
    line_no: Optional[int] = None
    pattern: str
    problem_explanation: str            # why this breaks Cloud Manager specifically
    fix_code_example: str               # before/after or "add X to Y"
    owning_team: Literal["frontend", "backend", "ops", "dispatcher"]
    historical_occurrences: int = 0


class ScanReport(BaseModel):
    repo_scanned: str
    total_findings: int
    p1_count: int
    p2_count: int
    p3_count: int
    findings: List[ScanFinding] = Field(default_factory=list)
    deployment_readiness: Literal["BLOCK", "WARN", "PASS"]
    summary: str                        # 2 sentences max


# ── Feature 5b: Pinpoint Report ──────────────────────────────────────────────

class PinpointReport(BaseModel):
    execution_id: str
    failed_step: str
    error_type: str
    primary_cause_file: str
    primary_cause_line_no: Optional[int] = None
    primary_cause_line: Optional[str] = None
    explanation: str
    fix_before: Optional[str] = None   # code snippet — current broken state
    fix_after: Optional[str] = None    # code snippet — corrected state
    prevention: str
    confidence: Literal["High", "Medium", "Low"]
    alternative_causes: List[dict] = Field(default_factory=list)
